package com.yaroslavzghoba.achromatic_material.color

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class ColorScheme(
    val achromatic: Color,
    val onAchromatic: Color,
    val achromaticContainer: Color,
    val onAchromaticContainer: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val surfaceBright: Color,
    val surfaceDim: Color,
    val surfaceContainerLowest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val onSurface: Color,
    val onSurfaceVariant: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
)

fun lightColorScheme(
    achromatic: Color = ColorLightTokens.Achromatic,
    onAchromatic: Color = ColorLightTokens.OnAchromatic,
    achromaticContainer: Color = ColorLightTokens.AchromaticContainer,
    onAchromaticContainer: Color = ColorLightTokens.OnAchromaticContainer,
    error: Color = ColorLightTokens.Error,
    onError: Color = ColorLightTokens.OnError,
    errorContainer: Color = ColorLightTokens.ErrorContainer,
    onErrorContainer: Color = ColorLightTokens.OnErrorContainer,
    background: Color = ColorLightTokens.Background,
    onBackground: Color = ColorLightTokens.OnBackground,
    surface: Color = ColorLightTokens.Surface,
    surfaceBright: Color = ColorLightTokens.SurfaceBright,
    surfaceDim: Color = ColorLightTokens.SurfaceDim,
    surfaceContainerLowest: Color = ColorLightTokens.SurfaceContainerLowest,
    surfaceContainerLow: Color = ColorLightTokens.SurfaceContainerLow,
    surfaceContainer: Color = ColorLightTokens.SurfaceContainer,
    surfaceContainerHigh: Color = ColorLightTokens.SurfaceContainerHigh,
    surfaceContainerHighest: Color = ColorLightTokens.SurfaceContainerHighest,
    onSurface: Color = ColorLightTokens.OnSurface,
    onSurfaceVariant: Color = ColorLightTokens.OnSurfaceVariant,
    outline: Color = ColorLightTokens.Outline,
    outlineVariant: Color = ColorLightTokens.OutlineVariant,
    scrim: Color = ColorLightTokens.Scrim,
): ColorScheme = ColorScheme(
    achromatic = achromatic,
    onAchromatic = onAchromatic,
    achromaticContainer = achromaticContainer,
    onAchromaticContainer = onAchromaticContainer,
    error = error,
    onError = onError,
    errorContainer = errorContainer,
    onErrorContainer = onErrorContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    surfaceBright = surfaceBright,
    surfaceDim = surfaceDim,
    surfaceContainerLowest = surfaceContainerLowest,
    surfaceContainerLow = surfaceContainerLow,
    surfaceContainer = surfaceContainer,
    surfaceContainerHigh = surfaceContainerHigh,
    surfaceContainerHighest = surfaceContainerHighest,
    onSurface = onSurface,
    onSurfaceVariant = onSurfaceVariant,
    outline = outline,
    outlineVariant = outlineVariant,
    scrim = scrim,
)

fun darkColorScheme(
    achromatic: Color = ColorDarkTokens.Achromatic,
    onAchromatic: Color = ColorDarkTokens.OnAchromatic,
    achromaticContainer: Color = ColorDarkTokens.AchromaticContainer,
    onAchromaticContainer: Color = ColorDarkTokens.OnAchromaticContainer,
    error: Color = ColorDarkTokens.Error,
    onError: Color = ColorDarkTokens.OnError,
    errorContainer: Color = ColorDarkTokens.ErrorContainer,
    onErrorContainer: Color = ColorDarkTokens.OnErrorContainer,
    background: Color = ColorDarkTokens.Background,
    onBackground: Color = ColorDarkTokens.OnBackground,
    surface: Color = ColorDarkTokens.Surface,
    surfaceBright: Color = ColorDarkTokens.SurfaceBright,
    surfaceDim: Color = ColorDarkTokens.SurfaceDim,
    surfaceContainerLowest: Color = ColorDarkTokens.SurfaceContainerLowest,
    surfaceContainerLow: Color = ColorDarkTokens.SurfaceContainerLow,
    surfaceContainer: Color = ColorDarkTokens.SurfaceContainer,
    surfaceContainerHigh: Color = ColorDarkTokens.SurfaceContainerHigh,
    surfaceContainerHighest: Color = ColorDarkTokens.SurfaceContainerHighest,
    onSurface: Color = ColorDarkTokens.OnSurface,
    onSurfaceVariant: Color = ColorDarkTokens.OnSurfaceVariant,
    outline: Color = ColorDarkTokens.Outline,
    outlineVariant: Color = ColorDarkTokens.OutlineVariant,
    scrim: Color = ColorDarkTokens.Scrim,
): ColorScheme = ColorScheme(
    achromatic = achromatic,
    onAchromatic = onAchromatic,
    achromaticContainer = achromaticContainer,
    onAchromaticContainer = onAchromaticContainer,
    error = error,
    onError = onError,
    errorContainer = errorContainer,
    onErrorContainer = onErrorContainer,
    background = background,
    onBackground = onBackground,
    surface = surface,
    surfaceBright = surfaceBright,
    surfaceDim = surfaceDim,
    surfaceContainerLowest = surfaceContainerLowest,
    surfaceContainerLow = surfaceContainerLow,
    surfaceContainer = surfaceContainer,
    surfaceContainerHigh = surfaceContainerHigh,
    surfaceContainerHighest = surfaceContainerHighest,
    onSurface = onSurface,
    onSurfaceVariant = onSurfaceVariant,
    outline = outline,
    outlineVariant = outlineVariant,
    scrim = scrim,
)

internal val LocalColorScheme = staticCompositionLocalOf { lightColorScheme() }
